steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/sandbox-337508/marcopolo-mockup/marcopolo-mockup', '-f', '_archive/mockup/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast1-docker.pkg.dev/sandbox-337508/marcopolo-mockup/marcopolo-mockup']
images:
  - 'asia-northeast1-docker.pkg.dev/sandbox-337508/marcopolo-mockup/marcopolo-mockup'
