steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/sandbox-337508/marcopolo-mockup', '-f', 'mockup/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/sandbox-337508/marcopolo-mockup']

